trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    cd backend
    dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: |
    cd backend
    cd sonar
    ls
    sonar-analise.sh
  displayName: 'Backend SonarLint'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    cd achei-app
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
